core/Form/Site/MenuType.php
<?php

namespace App\Core\Form\Site;

use App\Core\Entity\Site\Menu;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\NotBlank;

class MenuType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add(
            'label',
            TextType::class,
            [
                'label' => 'Label',
                'required' => true,
                'attr' => [
                ],
                'constraints' => [
                    new NotBlank(),
                ],
            ]
        );

        $builder->add(
            'code',
            TextType::class,
            [
                'label' => 'Code',
                'required' => true,
                'attr' => [
                ],
                'constraints' => [
                    new NotBlank(),
                ],
            ]
        );
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Menu::class,
        ]);
    }
}

core/Form/Site/NavigationAdditionalDomainType.php
<?php

namespace App\Core\Form\Site;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\NotBlank;

class NavigationAdditionalDomainType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add(
            'domain',
            TextType::class,
            [
                'label' => 'Domain',
                'required' => true,
                'help' => 'Regular expression: do not add the delimiter',
                'attr' => [
                ],
                'constraints' => [
                    new NotBlank(),
                ],
            ]
        );

        $builder->add(
            'type',
            ChoiceType::class,
            [
                'label' => 'Type',
                'required' => true,
                'choices' => [
                    'Domain' => 'domain',
                    'Regular expression' => 'regexp',
                ],
                'attr' => [
                ],
                'constraints' => [
                    new NotBlank(),
                ],
            ]
        );
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
        ]);
    }
}

core/Form/Site/NavigationType.php
<?php

namespace App\Core\Form\Site;

use App\Core\Entity\Site\Navigation;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;

class NavigationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add(
            'label',
            TextType::class,
            [
                'label' => 'Label',
                'required' => true,
                'attr' => [
                ],
                'constraints' => [
                    new NotBlank(),
                ],
            ]
        );

        $builder->add(
            'code',
            TextType::class,
            [
                'label' => 'Code',
                'required' => true,
                'attr' => [
                ],
                'constraints' => [
                    new NotBlank(),
                ],
            ]
        );

        $builder->add(
            'domain',
            TextType::class,
            [
                'label' => 'Domain',
                'required' => true,
                'attr' => [
                ],
                'constraints' => [
                    new NotBlank(),
                ],
            ]
        );

        $builder->add(
            'forceDomain',
            CheckboxType::class,
            [
                'label' => 'Force this domain',
                'required' => false,
                'attr' => [
                ],
                'constraints' => [
                ],
            ]
        );

        $builder->add(
            'additionalDomains',
            CollectionType::class,
            [
                'entry_type' => NavigationAdditionalDomainType::class,
                'label' => 'Additional domains',
                'by_reference' => false,
                'allow_add' => true,
                'allow_delete' => true,
                'prototype' => true,
            ]
        );

        $builder->add(
            'locale',
            TextType::class,
            [
                'label' => 'Locale',
                'required' => true,
                'attr' => [
                ],
                'constraints' => [
                    new NotBlank(),
                    new Length(['min' => 2, 'max' => 10]),
                ],
            ]
        );
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Navigation::class,
        ]);
    }
}

core/Form/Site/NodeAttributeType.php
<?php

namespace App\Core\Form\Site;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\NotBlank;

class NodeAttributeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add(
            'label',
            TextType::class,
            [
                'label' => 'Label',
                'required' => true,
                'attr' => [
                ],
                'constraints' => [
                    new NotBlank(),
                ],
            ]
        );

        $builder->add(
            'value',
            TextType::class,
            [
                'label' => 'Value',
                'required' => false,
                'attr' => [
                ],
                'constraints' => [
                ],
            ]
        );
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => null,
        ]);
    }
}

core/Form/Site/NodeMoveType.php
<?php

namespace App\Core\Form\Site;

use App\Core\Entity\Site\Node;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\NotBlank;

class NodeMoveType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add(
            'position',
            ChoiceType::class,
            [
                'label' => 'Position',
                'required' => true,
                'choices' => [
                    'After' => 'after',
                    'Before' => 'before',
                    'Above' => 'above',
                ],
                'attr' => [
                ],
                'constraints' => [
                    new NotBlank(),
                ],
            ]
        );

        $builder->add(
            'node',
            EntityType::class,
            [
                'label' => 'Element',
                'class' => Node::class,
                'choices' => call_user_func(function () use ($options) {
                    return $options['menu']->getRootNode()->getAllChildren();
                }),
                'choice_label' => 'treeLabel',
                'attr' => [
                ],
                'constraints' => [
                    new NotBlank(),
                ],
            ]
        );
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => null,
            'menu' => null,
        ]);
    }
}

core/Form/Site/NodeParameterType.php
<?php

namespace App\Core\Form\Site;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\NotBlank;

class NodeParameterType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add(
            'name',
            TextType::class,
            [
                'label' => 'Name',
                'required' => true,
                'attr' => [
                ],
                'constraints' => [
                    new NotBlank(),
                ],
            ]
        );

        $builder->add(
            'defaultValue',
            TextType::class,
            [
                'label' => 'Default value',
                'required' => false,
                'attr' => [
                ],
                'constraints' => [
                ],
            ]
        );

        $builder->add(
            'requirement',
            TextType::class,
            [
                'label' => 'Requirement',
                'help' => 'Regular expression',
                'required' => false,
                'attr' => [
                ],
                'constraints' => [
                ],
            ]
        );
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => null,
        ]);
    }
}

core/Form/Site/NodeSitemapParametersType.php
<?php

namespace App\Core\Form\Site;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\NotBlank;

class NodeSitemapParametersType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add(
            'isVisible',
            CheckboxType::class,
            [
                'label' => 'Visible',
                'required' => false,
                'attr' => [
                ],
                'constraints' => [
                ],
            ]
        );

        $builder->add(
            'priority',
            ChoiceType::class,
            [
                'label' => 'Priority',
                'required' => true,
                'attr' => [
                ],
                'choices' => call_user_func(function () {
                    $choices = [];

                    for ($u = 0; $u <= 10; ++$u) {
                        $choices[$u] = $u / 10;
                    }

                    return $choices;
                }),
                'constraints' => [
                    new NotBlank(),
                ],
            ]
        );

        $builder->add(
            'changeFrequency',
            ChoiceType::class,
            [
                'label' => 'Frequency of change',
                'required' => true,
                'attr' => [
                ],
                'choices' => [
                    'Toujours' => 'always',
                    'Toutes les heures' => 'hourly',
                    'Quotidienne' => 'daily',
                    'Hebdomadaire' => 'weekly',
                    'Mensuelle' => 'monthly',
                    'Annuelle' => 'yearly',
                    'Jamais' => 'never',
                ],
                'constraints' => [
                    new NotBlank(),
                ],
            ]
        );
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => null,
        ]);
    }
}

core/Form/Site/Page/ChoiceBlockType.php
<?php

namespace App\Core\Form\Site\Page;

use App\Core\Entity\Site\Page\ChoiceBlock;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ChoiceBlockType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add(
            'value',
            ChoiceType::class,
            array_merge([
                'required' => false,
                'label' => false,
            ], $options['options']),
        );
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => ChoiceBlock::class,
            'options' => [],
        ]);
    }
}

core/Form/Site/Page/CollectionBlockType.php
<?php

namespace App\Core\Form\Site\Page;

use App\Core\Entity\Site\Page\Block;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CollectionBlockType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add(
            'value',
            $options['collection_type'],
            array_merge([
                'required' => false,
                'label' => false,
            ], $options['options']),
        );
    }

    /**
     * {@inheritdoc}
     */
    public function buildView(FormView $view, FormInterface $form, array $options)
    {
        $view->vars = array_replace($view->vars, [
            'collection_name' => $options['collection_name'],
            'label_add' => $options['label_add'],
            'label_delete' => $options['label_delete'],
        ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Block::class,
            'collection_type' => CollectionType::class,
            'collection_name' => '',
            'label_add' => 'Add',
            'label_delete' => 'Delete',
            'options' => [],
        ]);
    }
}

core/Form/Site/Page/FileBlockType.php
<?php

namespace App\Core\Form\Site\Page;

use App\Core\Entity\Site\Page\FileBlock;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class FileBlockType extends TextBlockType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add(
            'value',
            FileType::class,
            array_merge([
                'required' => false,
                'label' => false,
            ], $options['options']),
        );
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => FileBlock::class,
            'block_prefix' => 'file_block',
            'options' => [],
        ]);
    }
}

core/Controller/Task/TaskAdminController.php
<?php

namespace App\Core\Controller\Task;

use App\Core\Controller\Admin\AdminController;
use App\Core\Event\Task\TaskInitEvent;
use App\Core\Event\Task\TaskRunRequestedEvent;
use SensioLabs\AnsiConverter\AnsiToHtmlConverter;
use SensioLabs\AnsiConverter\Theme\SolarizedTheme;
use Symfony\Component\Console\Output\BufferedOutput;
use Symfony\Component\EventDispatcher\EventDispatcherInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/admin/task")
 */
class TaskAdminController extends AdminController
{
    /**
     * @Route("/", name="admin_task_index")
     */
    public function index(EventDispatcherInterface $eventDispatcher): Response
    {
        $event = new TaskInitEvent();
        $eventDispatcher->dispatch($event, TaskInitEvent::INIT_EVENT);

        return $this->render('@Core/task/task_admin/index.html.twig', [
            'pager' => $event->getTasks(),
        ]);
    }

    /**
     * @Route("/run/{task}", name="admin_task_run", methods={"GET"})
     */
    public function run(
        string $task,
        Request $request,
        EventDispatcherInterface $eventDispatcher
    ): Response {
        if (!$this->isCsrfTokenValid('task_run', $request->query->get('_token'))) {
            throw $this->createAccessDeniedException();
        }

        $output = new BufferedOutput();
        $event = new TaskRunRequestedEvent($task, $request->query, $output);
        $eventDispatcher->dispatch($event, TaskRunRequestedEvent::RUN_REQUEST_EVENT);

        $converter = new AnsiToHtmlConverter(new SolarizedTheme());
        $content = $converter->convert($output->fetch());

        return $this->render('@Core/task/task_admin/run.html.twig', [
            'output' => $content,
        ]);
    }

    public function getSection(): string
    {
        return 'task';
    }
}

core/Resources/views/site/navigation_admin/_form.html.twig
<div class="row">
    <div class="col-12 p-3">
        <div class="row">
            {% for item in ['label', 'locale', 'code'] %}
                <div class="col-12">
                    {{ form_row(form[item]) }}
                </div>
            {% endfor %}

            <div class="col-12">
                {{ form_row(form.domain) }}
            </div>
            <div class="col-12">
                {{ form_row(form.forceDomain) }}
            </div>

            {% set collection_name = 'additional-domains' %}
            {% set label_add = 'Add' %}
            {% set label_delete = 'Delete' %}

            <div data-collection="collection-{{ collection_name }}" class="col-12">
                {{ form_label(form.additionalDomains) }}

                {% for item in form.additionalDomains %}
                    <div data-collection-item="{{ loop.index }}">
                        <div class="row">
                            {% for child in item %}
                                <div class="col-12 col-md-3 pr-3">
                                    {{ form_row(child) }}
                                </div>
                            {% endfor %}

                            <div class="col-12 col-md-3">
                                <span data-collection-delete-container class="btn btn-sm btn-danger" style="margin-top: 2.1rem">
                                    <span data-collection-delete="{{ loop.index }}">
                                        {{ label_delete|trans }}
                                    </span>
                                </span>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div data-collection-add="collection-{{ collection_name }}" class="collection-add col-12">
                <span class="btn btn-sm btn-primary" data-collection-add="collection-{{ collection_name }}">
                    {{ label_add|trans }}
                </span>
            </div>
            <template type="text/template" id="collection-{{ collection_name }}">
                <div data-collection-item="__name__">
                    <div class="row">
                        {% for child in form.additionalDomains.vars.prototype %}
                            <div class="col-12 col-md-3 pr-3">
                                {{ form_row(child) }}
                            </div>
                        {% endfor %}

                        <div class="col-12 col-md-3">
                            <span data-collection-delete-container class="btn btn-sm btn-danger" style="margin-top: 2.1rem">
                                {{ label_delete|trans }}
                            </span>
                        </div>
                    </div>
                </div>
            </template>
        </div>
    </div>
</div>

<div class="d-none">
    {{ form_rest(form) }}
</div>

core/Resources/views/site/navigation_admin/_show.html.twig
{% set datas = configuration.viewDatas(context) %}

<div class="row">
    <div class="col-12 p-3">
        <ul class="list-group">
            <li class="list-group-item">
                <div class="row">
                    <div class="col-md-4">
                        <span class="font-weight-bold pb-2 d-block">{{ 'Label'|trans }}</span>
                        {{ entity.label }}
                    </div>
                    <div class="col-md-4">
                        <span class="font-weight-bold pb-2 d-block">{{ 'Locale'|trans }}</span>
                        {{ entity.locale }}
                    </div>
                    <div class="col-md-4">
                        <span class="font-weight-bold pb-2 d-block">{{ 'Code'|trans }}</span>
                        {{ entity.code }}
                    </div>
                </div>
            </li>

            <li class="list-group-item">
                <div class="mb-3">
                    <span class="font-weight-bold pb-2 d-block">{{ 'Domain'|trans }}</span>
                    {{ entity.domain }}
                </div>
                <div>
                    {% set additionalDomains = entity.additionalDomains %}

                    <span class="font-weight-bold pb-2 d-block">{{ 'Additional domains'|trans }}</span>

                    {% for item in additionalDomains %}
                        <div>
                            {{ item.domain }}

                            {% if item.type == 'domain' %}
                                ({{ 'Domain'|trans|lower }})
                            {% else %}
                                ({{ 'Regular expression'|trans|lower }})
                                {% endif %}
                            </div>
                        {% else %}
                            -
                        {% endfor %}
                    </div>
            </li>
        </ul>
    </div>

    <div class="table-responsive">
        <table class="table">
            <thead class="thead-light">
                <tr>
                    <th class="col-5">{{ 'Label'|trans }}</th>
                    <th class="col-5">{{ 'Section'|trans }}</th>
                    <th class="col-2 miw-100 text-right">{{ 'Actions'|trans }}</th>
                </tr>
            </thead>
            <tbody>
                {% for item in datas.settings %}
                    {% set edit = path('admin_navigation_setting_edit', {entity: item.id}) %}

                    <tr data-dblclick="{{ edit }}">
                        <td class="col-5">
                            <a href="#" data-modal="{{ edit }}" class="font-weight-bold text-body d-block">
                                {{ item.label|trans }}
                            </a>
                        </td>
                        <td class="col-5">
                            <span class="btn btn-light">{{ item.section|trans }}</span>
                        </td>
                        <td class="col-2 miw-100 text-right">
                            <span data-modal="{{ edit }}" class="btn btn-sm btn-primary mr-1">
                                <span data-modal="{{ edit }}" class="fa fa-edit"></span>
                            </span>
                            <button type="submit" form="form-delete-{{ item.id }}" class="btn btn-sm btn-danger">
                                <span class="fa fa-trash"></span>
                            </button>

                            <form method="post" action="{{ path('admin_navigation_setting_delete', {entity: item.id}) }}" id="form-delete-{{ item.id }}" data-form-confirm>
                                <input type="hidden" name="_method" value="DELETE">
                                <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ item.id) }}">
                            </form>
                        </td>
                    </tr>
                {% else %}
                    <tr>
                        <td class="col-12 text-center p-4 text-black-50" colspan="3">
                            <div class="display-1">
                                <span class="fa fa-search"></span>
                            </div>
                            <div class="display-5 mt-3">
                                {{ 'No result'|trans }}
                            </div>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

core/Resources/views/site/navigation_admin/index.html.twig
{% extends '@Core/admin/crud/index.html.twig' %}

{% block header_actions_before %}
    <a href="{{ path(configuration.pageRoute('redirects'), configuration.pageRouteParams('redirects')) }}" class="btn btn-light">
        <span class="fa fa-map-signs pr-1"></span>
        {{ configuration.actionTitle(context, 'redirects', 'Redirects')|trans }}
    </a>
{% endblock %}

{% block list_item_actions_before %}
    <a href="{{ path('admin_site_tree_navigation', {navigation: item.id}) }}" class="btn btn-sm btn-success mr-1">
        <span class="fa fa-sitemap"></span>
    </a>
{% endblock %}

core/Resources/views/site/navigation_admin/show.html.twig
{% extends '@Core/admin/crud/show.html.twig' %}

{% block header_actions_after %}
    <a href="{{ path('admin_site_tree_navigation', {navigation: entity.id}) }}" class="btn btn-success">
        <span class="fa fa-sitemap"></span>
        {{ 'Tree'|trans }}
    </a>
{% endblock %}